concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }} @ ${{ github.ref }}
jobs:
  Fuzzing:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: build
      name: Build Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/build_fuzzers@master
      with:
        dry-run: false
        language: jvm
        oss-fuzz-project-name: jackson-databind
    - continue-on-error: true
      name: Run Fuzzers
      uses: google/oss-fuzz/infra/cifuzz/actions/run_fuzzers@master
      with:
        dry-run: false
        fuzz-seconds: 1200
        language: jvm
        oss-fuzz-project-name: jackson-databind
    - continue-on-error: true
      if: failure() && steps.build.outcome == 'success'
      name: Upload Crash
      uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808
      with:
        name: artifacts
        path: ./out/artifacts
name: CIFuzz
on:
  repository_dispatch:
    types: trigger-ga___cifuzz.yml
permissions: {}
