jobs:
  build:
    env:
      JAVA_OPTS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9
      with:
        cache: maven
        distribution: temurin
        java-version: ${{ matrix.java_version }}
    - continue-on-error: true
      name: Build and test
      run: ./mvnw -B -ff -ntp verify
    strategy:
      fail-fast: false
      matrix:
        java_version:
        - '8'
        - '17'
        - '21'
        os:
        - ubuntu-22.04
  trigger-dep-build:
    name: Trigger downstream builds
    needs:
    - build
    secrets:
      token: ${{ secrets.REPO_DISPATCH }}
    uses: ./.github/workflows/trigger_dep_builds.yml
name: Re-build on jackson-core push
on:
  repository_dispatch:
    types: trigger-ga___dep_build.yml
permissions:
  contents: read
