jobs:
  trigger-dep-build:
    name: Trigger downstream builds
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Repository dispatch
      uses: peter-evans/repository-dispatch@v3
      with:
        client-payload: '{"version": "N/A" }'
        event-type: jackson-databind-pushed
        repository: ${{ matrix.repo }}
        token: ${{ secrets.token }}
    - continue-on-error: true
      name: Delay between dispatches
      run: sleep 10s
      shell: bash
    strategy:
      fail-fast: false
      matrix:
        repo:
        - FasterXML/jackson-modules-base
        - FasterXML/jackson-dataformats-binary
        - FasterXML/jackson-dataformats-text
        - FasterXML/jackson-dataformat-xml
        - FasterXML/jackson-datatypes-collections
        - FasterXML/jackson-datatypes-misc
        - FasterXML/jackson-module-kotlin
        - FasterXML/jackson-module-scala
      max-parallel: 1
name: Trigger downstream builds
on:
  repository_dispatch:
    types: trigger-ga___trigger_dep_builds.yml
